### ISSUE TITLE
<AP> Pry Tool 

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Accessory-Issue#1]
When will it come along with dash cam, being packed in the same retail box?

**Comment by dod-pm1** [comment]
Currently processing with manufacturer if we can change color as well as required MOQ.
Will further update this by June 7.
And yes it will be packed in the same retail box, it fits just fine.
However, does sales dept. decide with large or small, or both yet?

**Comment by dod-pm1** [comment]
Newer updates, large pry bar will be changed to green color, smaller pry tool remains blue.
Will include both in pkg, as sales has agreed, ONLY dual cam model will contain these pry tools.
Further update next week with extimated date for this to be done.

**Comment by DOD-AP-Sales** [comment]
update?

**Comment by dod-pm1** [comment]
Just FYI, as info updated in person, we switch company for this pry tool, should be able to include in the package in mid to end of July.

**Comment by DOD-AP-Sales** [comment]
Included the pry tool to dual cams on Sep 20th.
