### ISSUE TITLE
<AP> Plastic Bag for DV2 

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Accessory-Issue#2]
When can DV2 be packed? Now it is naked lying in the box of the RC500S.

**Comment by dod-pm1** [comment]
They have tried similar bags, but now facing a problem that the car charger will be pushed up slightly.
Shipment will arrive around 19th-21th.

**Comment by DOD-AP-Sales** [comment]
Remember to pack the car charger as well. Thanks.

**Comment by dod-pm1** [comment]
Will do, Paul will help to track this update while I am away, once the bags arrive, please contact Nick for this issue.
Agree to close?

**Comment by DOD-AP-Sales** [comment]
Agreed.
