### ISSUE TITLE
<EU> IS420W mount

### ISSUE THREAD

**Issue by DOD-EU-SALES** [dod-taiwan/Accessory-Issue#5]
need a new mount for the IS420W, as the current one is not suitable for stead windshields such as truck and bus,  Is there any news?

**Comment by dod-pm1** [comment]
As pic sent via wechat, the mount was made back in 2013, should have some left to cover for now.
Not suggested to extend current Gecko mount, once the arm extends, the vibration will also increase.
Use conventional mount with suction savior is more likely to be the best solution in this case.
