### ISSUE TITLE
<NA> DP4 hardwiring cable caused the car battery drained

### ISSUE THREAD

**Issue by DOD-NA-SALES** [dod-taiwan/Accessory-Issue#6]
The car engine can not start.
![wechat _20170804091226](https://user-images.githubusercontent.com/29187917/29010895-5c64b618-7b61-11e7-8556-2a6aeae73f1f.jpg)
![wechat _20170804091221](https://user-images.githubusercontent.com/29187917/29010894-5c620030-7b61-11e7-9dd5-a67a87fd3ee7.jpg)

Video below shows LS500W before battery dies.
https://www.asuswebstorage.com/navigate/s/5C724765A6694F1CB936367ABE9F2F824

**Comment by dod-pm1** [comment]
As discussed on SKYPE, this is more likely to be caused by a defected unit.
Let's try to get that unit back first.
Tested in CHINA, unit seems working properly, we will take a look at the actual unit before further call.

**Comment by dod-pm1** [comment]
according to your info as told in person, resulted in client's faulty battery. Case close.
